let electron = require("electron");
//#region electron/preload.mjs
electron.contextBridge.exposeInMainWorld("electronAPI", {
	getJobs: () => electron.ipcRenderer.invoke("get-jobs"),
	getJob: (id) => electron.ipcRenderer.invoke("get-job", id),
	createJob: (job) => electron.ipcRenderer.invoke("create-job", job),
	updateJob: (id, fields) => electron.ipcRenderer.invoke("update-job", id, fields),
	getActivities: () => electron.ipcRenderer.invoke("get-activities"),
	getWorkers: () => electron.ipcRenderer.invoke("get-workers"),
	getTerminalLines: (jobId) => electron.ipcRenderer.invoke("get-terminal-lines", jobId),
	getToolStatuses: () => electron.ipcRenderer.invoke("get-tool-statuses"),
	refreshToolStatuses: () => electron.ipcRenderer.invoke("refresh-tool-statuses"),
	getToolSetupCompleted: () => electron.ipcRenderer.invoke("get-tool-setup-completed"),
	setToolSetupCompleted: (completed) => electron.ipcRenderer.invoke("set-tool-setup-completed", completed),
	saveToolSecret: (payload) => electron.ipcRenderer.invoke("save-tool-secret", payload),
	runToolAction: (payload) => electron.ipcRenderer.invoke("run-tool-action", payload),
	runTask: (taskId, agent, workdir) => electron.ipcRenderer.invoke("run-task", {
		taskId,
		agent,
		workdir
	}),
	cancelTask: (taskId) => electron.ipcRenderer.invoke("cancel-task", taskId),
	killAll: () => electron.ipcRenderer.invoke("kill-all"),
	runRace: (taskId, agents, workdir) => electron.ipcRenderer.invoke("run-race", {
		taskId,
		agents,
		workdir
	}),
	mergeTask: (taskId) => electron.ipcRenderer.invoke("merge-task", taskId),
	discardTask: (taskId) => electron.ipcRenderer.invoke("discard-task", taskId),
	getMcpServers: () => electron.ipcRenderer.invoke("get-mcp-servers"),
	getCapabilityRegistry: () => electron.ipcRenderer.invoke("get-capability-registry"),
	testMcpServerConnection: (server) => electron.ipcRenderer.invoke("test-mcp-server-connection", server),
	addMcpServer: (server) => electron.ipcRenderer.invoke("add-mcp-server", server),
	updateMcpServer: (id, fields) => electron.ipcRenderer.invoke("update-mcp-server", id, fields),
	deleteMcpServer: (id) => electron.ipcRenderer.invoke("delete-mcp-server", id),
	getCredentials: () => electron.ipcRenderer.invoke("get-credentials"),
	addCredential: (cred) => electron.ipcRenderer.invoke("add-credential", cred),
	deleteCredential: (id) => electron.ipcRenderer.invoke("delete-credential", id),
	getSkills: () => electron.ipcRenderer.invoke("get-skills"),
	addSkill: (skill) => electron.ipcRenderer.invoke("add-skill", skill),
	updateSkill: (id, fields) => electron.ipcRenderer.invoke("update-skill", id, fields),
	deleteSkill: (id) => electron.ipcRenderer.invoke("delete-skill", id),
	getPlugins: () => electron.ipcRenderer.invoke("get-plugins"),
	addPlugin: (plugin) => electron.ipcRenderer.invoke("add-plugin", plugin),
	updatePlugin: (id, fields) => electron.ipcRenderer.invoke("update-plugin", id, fields),
	deletePlugin: (id) => electron.ipcRenderer.invoke("delete-plugin", id),
	togglePlugin: (id, enabled) => electron.ipcRenderer.invoke("toggle-plugin", id, enabled),
	getProjects: () => electron.ipcRenderer.invoke("get-projects"),
	getProject: (id) => electron.ipcRenderer.invoke("get-project", id),
	addProject: (project) => electron.ipcRenderer.invoke("add-project", project),
	deleteProject: (id) => electron.ipcRenderer.invoke("delete-project", id),
	setActiveProject: (id) => electron.ipcRenderer.invoke("set-active-project", id),
	getSettings: () => electron.ipcRenderer.invoke("get-settings"),
	setSetting: (key, value) => electron.ipcRenderer.invoke("set-setting", key, value),
	showOpenDialog: () => electron.ipcRenderer.invoke("show-open-dialog"),
	openExternal: (url) => electron.ipcRenderer.invoke("open-external", url),
	startPreviewServer: (taskId) => electron.ipcRenderer.invoke("start-preview-server", taskId),
	stopPreviewServer: (taskId) => electron.ipcRenderer.invoke("stop-preview-server", taskId),
	onTaskOutput: (cb) => electron.ipcRenderer.on("task-output", (_e, taskId, chunk) => cb(taskId, chunk)),
	onTaskDone: (cb) => electron.ipcRenderer.on("task-done", (_e, taskId, result) => cb(taskId, result)),
	onStateChanged: (cb) => electron.ipcRenderer.on("state-changed", () => cb()),
	onRuntimeTick: (cb) => electron.ipcRenderer.on("runtime-tick", (_e, runtimes) => cb(runtimes)),
	onRaceOutput: (cb) => electron.ipcRenderer.on("race-output", (_e, taskId, agent, chunk) => cb(taskId, agent, chunk)),
	onRaceResult: (cb) => electron.ipcRenderer.on("race-result", (_e, taskId, agent, result) => cb(taskId, agent, result)),
	onPreviewReady: (cb) => electron.ipcRenderer.on("preview-ready", (_e, taskId, port, output) => cb(taskId, port, output)),
	onToolOutput: (cb) => electron.ipcRenderer.on("tool-output", (_e, toolId, sessionId, chunk) => cb(toolId, sessionId, chunk)),
	onToolActionStarted: (cb) => electron.ipcRenderer.on("tool-action-started", (_e, toolId, sessionId, kind) => cb(toolId, sessionId, kind)),
	onToolActionEnded: (cb) => electron.ipcRenderer.on("tool-action-ended", (_e, toolId, sessionId, exitCode, output) => cb(toolId, sessionId, exitCode, output)),
	onToolStatusesChanged: (cb) => electron.ipcRenderer.on("tool-statuses-changed", (_e, statuses) => cb(statuses)),
	removeAllListeners: (channel) => electron.ipcRenderer.removeAllListeners(channel)
});
//#endregion
